### ISSUE TITLE
Breaks ñ in Gmail on Mac

### ISSUE THREAD

**Issue by BMorearty** [Zemke/instant-smart-quotes#21]
On a Mac with a US keyboard, the ñ character can be entered by thing Option+n, followed by n. In Gmail on Mac, instant smart quotes breaks this behavior and results in ˜n being shown.

It doesn’t break other apps, such as this GitHub Issue entry box. 

Disabling instant smart quotes restores the correct behavior in Gmail.

**Comment by BMorearty** [comment]
This bug still occurs when this extension is enabled. Happens in Chrome but not Firefox. If you click the extension and choose “Switch OFF,” the problem stops.

**Comment by Zemke** [comment]
Thanks. Should be fixed. Please report back if it isn’t.
