### ISSUE TITLE
Description isn’t clear about what the app does and doesn’t

### ISSUE THREAD

**Issue by leeuwerck** [Zemke/instant-smart-quotes#25]
I was looking for an extension that replaces quotes in webpages. This one doesn’t seem to do so, as it replaces quotes in text written by the user. The description should clarify this.

**Comment by Zemke** [comment]
The first sentence in every description of the add-on I put out is “Replace typewriter quotes, apostrophes, ellipses and dashes with their typographically correct counterparts as you type.” That should be pretty obvious.
