### ISSUE TITLE
Disable within code blocks

### ISSUE THREAD

**Issue by GeoffreyBooth** [Zemke/instant-smart-quotes#4]
I love this extension. However, I paste code blocks into GitHub a lot, and I end up with pasted code like this:

```js
JSON.parse({ “key”: “val” });
```

I appreciate that the extension disables itself between single-backtick spans; could it also disable itself between triple-backtick spans/blocks? In other words, it should leave alone the code between the triple-backtick fences in Markdown, that look like this:

    ```js
    JSON.parse({ "key": "val" });
    ```

**Comment by Zemke** [comment]
Yeah, that would be great. Of course I’d already thought of that myself and now that I see more demand I feel like getting my hands on this.
