### ISSUE TITLE
Closing Quotes and Numbers

### ISSUE THREAD

**Issue by Varachack** [Zemke/instant-smart-quotes#6]
Good afternoon, @Zemke and @GeoffreyBooth.

This is a wonderful Chrome extension and I certainly do enjoy the convenience it provides, but I’d like to address a small issue I’ve been experiencing.

When contextually using closing quotes after a numerical value (to end a direct or indirect quote containing it), the quotations are not typographically corrected and instead remain as straight quotes. However when I use a single closing quote, there is no issue, and the same goes for when any other typographical symbol completes the sentence (succeeding a numerical value); the closing double quotation appears as such.

During conversation I noticed this, and here is a small excerpt:
## ‘Linda said the meeting **“wouldn’t be starting until 7,“** so get ready.’
But when succeeding the numerical value with nothing except quotations:
## ‘Linda said the meeting “wouldn’t be starting until 7" so get ready.’

Is there any way this can be corrected?
Thank you.

**Comment by Zemke** [comment]
Could potentially be fixed with #12.
