### ISSUE TITLE
Jumping caret on Facebook

### ISSUE THREAD

**Issue by Zemke** [Zemke/instant-smart-quotes#8]
> There’s a bug that occurs on Facebook that forces the cursor to the previous space preceding the first or second character that is typed after an em dash or ellipsis is typed, and so for instance, “…okay” would become “…kayo” or “…ayok” instead. So far this bug only occurs on Facebook and nowhere else.
>
> The bug manifests every single time either of these characters are typed and so I hope that this can be corrected since it is quite bothersome when it occurs while typing.

Chrome Web Store feedback
https://chrome.google.com/webstore/detail/instant-smart-quotes/dddflkfjemblhfmjdlmmilapbkdaabcj/support

**Comment by hboetes** [comment]
It's still there. Please fix this bug.
Or provide a workaround, so I can add Facebook to the list of sites where the app is not used.

**Comment by Zemke** [comment]
I cannot test on Facebook and apparently they’re doing crazy enough things with their input boxes. But this bug is also kinda old and Facebook might have changed their implementation and also Instant Smart Quotes has changed. So, maybe things work now—closing for now.

If nothing helps, you could also turn off ISM for Facebook and the setting is saved and shared across your devices.
