### ISSUE TITLE
Wrong leading typographical char on shortenings (i.e. ’99 or ’cause) 

### ISSUE THREAD

**Issue by Zemke** [Zemke/instant-smart-quotes#9]
> I noticed that while using this extension that an opening single quote is also typed when a shortened numerical year is written; i.e. “‘95" or 1995 should actually be “’95" in order to be typographically correct.
>
> The same thing occurs textually when shortened words like “’cause” (because) or “’til” (until) are written, where the improper apostrophe is placed instead of the closing single quote.

Chrome Web Store feedback
https://chrome.google.com/webstore/detail/instant-smart-quotes/dddflkfjemblhfmjdlmmilapbkdaabcj/support

**Comment by Varachack** [comment]
I just noticed that the other issue I highlighted about the improper closing quote being used for numerical values is actually present within this issue that I highlighted also. Heh, go figure. 😅

**Comment by Zemke** [comment]
Could potentially be fixed with #12.
